// A DOM smoke test, not a visual browser/screenshot acceptance test.
const fs=require('node:fs'), path=require('node:path'), vm=require('node:vm'), assert=require('node:assert/strict');
const text=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const payload=text.match(/<script id="bank" type="application\/json">([\s\S]*?)<\/script>/)[1];
const scripts=[...text.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(x=>x[1]);
assert.equal(scripts.length,1);
assert(!text.includes('<script src='), 'must work without CDN');
const elements=new Map();
function element(id){if(!elements.has(id))elements.set(id,{id,value:'',checked:false,innerHTML:'',textContent:'',disabled:false,options:[],attributes:{},listeners:{},add(o){this.options.push(o)},setAttribute(k,v){this.attributes[k]=v},addEventListener(k,fn){this.listeners[k]=fn}});return elements.get(id)}
element('bank').textContent=payload;
const storage=new Map();
const ctx=vm.createContext({document:{getElementById:element},Option:function(text,value){this.text=text;this.value=value},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},console,Math,JSON,Set,Object,String,Array});
vm.runInContext(scripts[0],ctx,{timeout:5000});
const run=source=>vm.runInContext(source,ctx,{timeout:5000});
const total=JSON.parse(payload).questions.length;
assert(!('sources' in JSON.parse(payload)));
assert(!text.includes('题目出处线索'));
assert.equal(run('filtered().length'),total);
assert.equal((element('cards').innerHTML.match(/<article /g)||[]).length,20);
assert.equal((element('cards').innerHTML.match(/class="answer-body"/g)||[]).length,20);
assert(!element('cards').innerHTML.includes('<details'));
assert(element('cards').innerHTML.includes('<math '));
element('search').value='LoRA';element('search').listeners.input();
assert(run('filtered().length')>0);
assert(run('filtered().every(q=>JSON.stringify(q).toLowerCase().includes("lora"))'));
element('reset').onclick();
element('category').value='VLM';element('category').listeners.change();
element('level').value='L2';element('level').listeners.change();
assert(run('filtered().every(q=>q.category==="VLM" && q.level==="L2")'));
element('random').onclick();assert(run('sample.length')<=10);
element('quiz').checked=true;element('quiz').onchange();
const card=element('cards').innerHTML;
assert(card.indexOf('<details')<card.indexOf('<div class="answer-body">'));
element('reset').onclick();
element('cards').onclick({target:{closest(){return {dataset:{star:'TFM-001'}}}}});
assert(storage.get('llm-interview-stars').includes('TFM-001'));
element('favorites').onclick();assert.equal(run('filtered().length'),1);
element('reset').onclick();
element('search').value='this-never-exists-8711';element('search').listeners.input();
assert.equal(run('filtered().length'),0);assert(element('cards').innerHTML.includes('没有匹配题目'));
assert(run('escapeHtml("<img onerror=alert(1)>")').startsWith('&lt;img'));
element('reset').onclick();element('next').onclick();assert(element('pageinfo').textContent.startsWith('2 /'));
console.log(`PASS: explorer DOM smoke tests; ${total} unified answers; search, categories, quiz, sampling, stars, paging, MathML and escaping`);
